name: mobile_team_project
description: "번호팅 - 익명 기반 대학생 매칭 & 채팅 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 카카오 SDK (팀원 코드)
  kakao_flutter_sdk: ^2.0.0+1
  kakao_flutter_sdk_user: ^2.0.0+1
  kakao_flutter_sdk_share: ^2.0.0+1
  kakao_flutter_sdk_talk: ^2.0.0+1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 카카오 로그인 버튼 이미지 (이미지 등록 후 주석 해제)
  # assets:
  #   - assets/images/kakao_login_medium_wide.png
